### ISSUE TITLE
Issue with RELATE builder generating CREATE statements

### ISSUE THREAD

**Issue by ghost** [syf20020816/Surrealism#1]
I've noticed building RELATE statements with the builder is actually resulting in CREATE statements, all else seems to be building appropriate .

After running:
        let relate = SQLBuilderFactory::relate()
        .table_from("users", SurrealID::from(name.to_lowercase()))
        .table_with("userkeys", SurrealID::Default)
        .table_to("pgpkeys", SurrealID::from(key_hash))
        .build();
        res = match service.commit_sql(&relate).await {
            Ok(User) => {"nice!".to_string()},
            Err(err) => {err.to_string()}
        };
        println!("{}", res);

Terminal output shows the CREATE statement:
CREATE users:bob123->userkeys->pgpkeys:16641677534007659253;

Here's the relevant source code from the Surrealism library:

#[derive(Debug, Clone)]
pub struct RelateWrapper {
    table_from: Table,
    table_with: Table,
    table_to: Table,
    content: Option<CreateStrategy>,
    return_type: Option<ReturnType>,
    timeout: Option<TimeOut>,
    parallel: bool,
}

impl BaseWrapperImpl for RelateWrapper {
    fn new() -> Self {
        RelateWrapper {
            table_from: Default::default(),
            table_with: Default::default(),
            table_to: Default::default(),
            content: None,
            return_type: None,
            timeout: None,
            parallel: false,
        }
    }

    fn deref_mut(&mut self) -> Self {
        RelateWrapper {
            table_from: self.table_from.clone(),
            table_with: self.table_with.clone(),
            table_to: self.table_to.clone(),
            content: self.content.clone(),
            return_type: self.return_type.clone(),
            timeout: self.timeout.clone(),
            parallel: self.parallel,

        }
    }

    fn build(&mut self) -> String {
        let mut res = format!("{} {}{}{}{}{}", CREATE, &self.table_from.combine(), LINK, &self.table_with.combine(), LINK, &self.table_to.combine());
        if self.content.is_some() {
            res.push_str(BLANK);
            res.push_str(&self.content.as_ref().unwrap().combine());
        }
        if self.return_type.is_some() {
            res.push_str(BLANK);
            res.push_str(&self.return_type.as_ref().unwrap().combine());
        }
        if self.timeout.is_some() {
            res.push_str(BLANK);
            res.push_str(&self.timeout.as_ref().unwrap().combine());
        }
        if self.parallel {
            res.push_str(BLANK);
            res.push_str(PARALLEL);
        }
        res.push_str(STMT_END);
        res
    }
}

**Comment by syf20020816** [comment]
You will receive this automatically generated email due to your feedback on Surrealism. Thank you again for raising the issue.

I  have noticed the current issue and plan to release V0.2.1 version  within 5 days to officially modify it. If this problem troubles you, you  can temporarily use row_ sql! macro to resolve

**Comment by ghost** [comment]
Great, awesome library! Keep up the great work!
